### ISSUE TITLE
Support to direct set the dig query type with domain when using Telegram bot

### ISSUE THREAD

**Issue by PeterDaveHello** [pengelana/blocklist#101]
Would be super helpful to use a single command like `/dig A www.google.com` or `/doh AAAA duck.com` without an additional query type selection, may I have this feature request? 😄

**Comment by pengelana** [comment]
Thank you for your request, I will think about it and see if we can add.

**Comment by PeterDaveHello** [comment]
Thank you @pengelana

**Comment by pengelana** [comment]
@PeterDaveHello, you may want to try again.

![image](https://user-images.githubusercontent.com/787301/156867874-c342aadc-127c-46af-abc8-38a048750471.png)

![image](https://user-images.githubusercontent.com/787301/156867882-95c0103e-2903-42ef-baf1-bf82da654056.png)

Support cloudflare, google and quad9 dns with command /1, /8 and /9

![image](https://user-images.githubusercontent.com/787301/156867936-66287232-ddda-43cb-95a7-38ad0d66be6f.png)

**Comment by PeterDaveHello** [comment]
@pengelana looks good to me, it works! Thanks!

**Comment by pengelana** [comment]
@PeterDaveHello, some tricks:

1. Query for PTR record with IPv4/IPv6 address without need to reverse the address.

![image](https://user-images.githubusercontent.com/787301/156917525-64df2947-e769-4ecc-a783-a1f9eb8b8d75.png)

![image](https://user-images.githubusercontent.com/787301/156917558-87a73969-a948-4f16-8152-4765f8a7e366.png)

![image](https://user-images.githubusercontent.com/787301/156917609-c9a2bfa5-32d4-4074-9d0d-f8aad985313d.png)

2. Query with URL instead of domain name (copy paste from browser).

![image](https://user-images.githubusercontent.com/787301/156917698-34011e65-f04c-441f-abae-2cbd9cf909c9.png)

![image](https://user-images.githubusercontent.com/787301/156917734-8fd6064d-6e52-460f-8160-a85dbf113915.png)

**Comment by PeterDaveHello** [comment]
@pengelana that's pretty cool and helpful!
