### ISSUE TITLE
*.kaskus.id won't resolve

### ISSUE THREAD

**Issue by SScape** [pengelana/blocklist#44]
s.kaskus.id and c.kaskus.id (Kaskus CDN) doesn't resolve, resulting in a broken kaskus webpage.

![image](https://user-images.githubusercontent.com/32894942/93278021-ae315580-f7ed-11ea-9dee-68c84447cbfa.png)

dig returns a SERVFAIL

![image](https://user-images.githubusercontent.com/32894942/93278081-d9b44000-f7ed-11ea-87db-562c0f005eac.png)

It resolves using other DNS just fine : 
![image](https://user-images.githubusercontent.com/32894942/93278244-521b0100-f7ee-11ea-8ef9-51f9b95b9bb4.png)

If this is intentional, kindly close this issue. Thanks.

**Comment by pengelana** [comment]
This problem could be caused by routing to Kaskus NS.

Back to normal after few hours.

![Screen Shot 2020-09-16 at 7 23 41 PM](https://user-images.githubusercontent.com/787301/93331232-84f6e080-f852-11ea-9589-a623beb60821.png)

![Screen Shot 2020-09-16 at 7 24 17 PM](https://user-images.githubusercontent.com/787301/93331270-917b3900-f852-11ea-8921-4f73457c2c8c.png)
